{
    "services": {
        "devcontainer": {
            "command": "sh -exc 'while sleep 1m; do :; done'",
            "image": "mcr.microsoft.com/devcontainers/javascript-node:18",
            "init": true,
            "volumes": [
                ".:/workspaces/jawa"
            ],
            "working_dir": "/workspaces/jawa"
        }
    }
}
